package com.example.mybird_test

import io.flutter.embedding.android.FlutterActivity

class MainActivity : FlutterActivity() {
    // flutroid:begin — generated by `flutroid init`; edits are overwritten
    override fun getFlutterShellArgs(): io.flutter.embedding.engine.FlutterShellArgs =
        dev.flutroid.FlutroidPatch.applyTo(this, super.getFlutterShellArgs())
    // flutroid:end
}
