/// Rewrites an app's `MainActivity` so the engine is offered the staged patch.
///
/// The generated override is the whole Android-side integration:
///
/// ```kotlin
/// override fun getFlutterShellArgs(): io.flutter.embedding.engine.FlutterShellArgs =
///     dev.flutroid.FlutroidPatch.applyTo(this, super.getFlutterShellArgs())
/// ```
///
/// `FlutterActivityAndFragmentDelegate` passes those args to
/// `FlutterEngineGroup`, which hands them to
/// `FlutterLoader.ensureInitializationComplete`, which splices them in ahead of
/// the entries for the bundled `libapp.so`. First one that resolves wins.
///
/// Types are written fully qualified so nothing has to be spliced into the
/// import list, and the block is fenced with markers so re-running `flutroid
/// init` regenerates it in place instead of duplicating it.
library;

const String beginMarker = '// flutroid:begin';
const String endMarker = '// flutroid:end';

/// What [patchMainActivity] did to a file.
enum PatchOutcome {
  /// The override was added to a file that did not have it.
  injected,

  /// A previous block was found and rewritten.
  regenerated,

  /// The file already held exactly this block.
  unchanged,
}

/// The result of a patch attempt.
class PatchResult {
  const PatchResult.success(this.outcome, this.source) : failure = null;

  const PatchResult.failure(this.failure) : outcome = null, source = null;

  final PatchOutcome? outcome;

  /// The rewritten file contents, or null when [failure] is set.
  final String? source;

  /// Why the file could not be patched, or null on success.
  final String? failure;

  bool get ok => failure == null;
}

/// Adds (or regenerates) the `getFlutterShellArgs` override in [source].
///
/// Returns a failure rather than a mangled file whenever the shape of the class
/// is not something this can rewrite confidently — the user's own code is not
/// worth a guess.
PatchResult patchMainActivity(String source, {required bool isKotlin}) {
  final block = isKotlin ? _kotlinBlock : _javaBlock;

  // Already integrated: swap the old block for the current one so an upgraded
  // CLI can fix up an app it patched before.
  final begin = source.indexOf(beginMarker);
  if (begin != -1) {
    final end = source.indexOf(endMarker, begin);
    if (end == -1) {
      return const PatchResult.failure(
        'found $beginMarker with no matching $endMarker — '
        'remove the leftover block by hand and re-run',
      );
    }
    final lineStart = source.lastIndexOf('\n', begin) + 1;
    final lineEnd = source.indexOf('\n', end);
    final existing = source.substring(lineStart, lineEnd == -1 ? source.length : lineEnd);
    final replacement = _indent(block, _leadingWhitespace(source, begin));
    if (existing == replacement.trimLeft() || existing == replacement) {
      return PatchResult.success(PatchOutcome.unchanged, source);
    }
    return PatchResult.success(
      PatchOutcome.regenerated,
      source.replaceRange(lineStart, lineEnd == -1 ? source.length : lineEnd, replacement),
    );
  }

  final declaration = RegExp(r'\bclass\s+MainActivity\b').firstMatch(source);
  if (declaration == null) {
    return const PatchResult.failure('no `class MainActivity` declaration found');
  }

  final bodyBrace = _findBodyBrace(source, declaration.end);
  if (bodyBrace == null) {
    if (!isKotlin) {
      // A Java class always has a body; not finding one means we misread the
      // file, and guessing would corrupt it.
      return const PatchResult.failure('could not locate the class body');
    }
    // `class MainActivity : FlutterActivity()` with no body — give it one.
    final insertAt = _endOfDeclaration(source, declaration.end);
    return PatchResult.success(
      PatchOutcome.injected,
      source.replaceRange(insertAt, insertAt, ' {\n${_indent(block, '    ')}\n}'),
    );
  }

  final closing = _matchingBrace(source, bodyBrace);
  if (closing == null) {
    return const PatchResult.failure('the class body has no matching closing brace');
  }

  final indent = _bodyIndent(source, bodyBrace, closing);
  final needsBlankLine = source.substring(bodyBrace + 1, closing).trim().isNotEmpty;
  final insertion = '${needsBlankLine ? '\n' : ''}${_indent(block, indent)}\n';
  final lineStart = source.lastIndexOf('\n', closing) + 1;
  return PatchResult.success(
    PatchOutcome.injected,
    source.replaceRange(lineStart, lineStart, insertion),
  );
}

const String _kotlinBlock = '''
$beginMarker — generated by `flutroid init`; edits are overwritten
override fun getFlutterShellArgs(): io.flutter.embedding.engine.FlutterShellArgs =
    dev.flutroid.FlutroidPatch.applyTo(this, super.getFlutterShellArgs())
$endMarker''';

const String _javaBlock = '''
$beginMarker — generated by `flutroid init`; edits are overwritten
@Override
public io.flutter.embedding.engine.FlutterShellArgs getFlutterShellArgs() {
    return dev.flutroid.FlutroidPatch.applyTo(this, super.getFlutterShellArgs());
}
$endMarker''';

String _indent(String block, String indent) =>
    block.split('\n').map((line) => line.isEmpty ? line : '$indent$line').join('\n');

String _leadingWhitespace(String source, int index) {
  final lineStart = source.lastIndexOf('\n', index) + 1;
  return source.substring(lineStart, index);
}

/// Indentation to use inside a class body, taken from the closing brace.
String _bodyIndent(String source, int open, int close) {
  final closeIndent = _leadingWhitespace(source, close);
  return '$closeIndent    ';
}

/// Index of the `{` opening the class body, or null if the class has none.
///
/// Walks the class header skipping comments, strings and parenthesised
/// supertype constructor calls. Anything that can only start a new top-level
/// declaration means the header ended without a body.
int? _findBodyBrace(String source, int from) {
  var depth = 0;
  var i = from;
  var atLineStart = false;

  while (i < source.length) {
    final skipped = _skipTrivia(source, i);
    if (skipped != i) {
      atLineStart = source.substring(i, skipped).contains('\n');
      i = skipped;
      continue;
    }

    final char = source[i];
    if (atLineStart && depth == 0 && _startsDeclaration(source, i)) return null;
    atLineStart = false;

    switch (char) {
      case '(':
      case '[':
        depth++;
      case ')':
      case ']':
        depth--;
      case '{':
        if (depth == 0) return i;
        depth++;
      case '}':
        if (depth == 0) return null;
        depth--;
    }
    i++;
  }
  return null;
}

/// True if a new declaration begins at [i], meaning the class header is over.
bool _startsDeclaration(String source, int i) {
  const starters = [
    'class ',
    'object ',
    'fun ',
    'val ',
    'var ',
    'interface ',
    'enum ',
    'private ',
    'internal ',
    'public ',
    'abstract ',
    'sealed ',
    'data ',
    'import ',
    '@',
  ];
  return starters.any((starter) => source.startsWith(starter, i));
}

/// End of a bodyless Kotlin class declaration — where a body would be added.
int _endOfDeclaration(String source, int from) {
  var depth = 0;
  var i = from;
  var lastToken = from;
  while (i < source.length) {
    final skipped = _skipTrivia(source, i);
    if (skipped != i) {
      i = skipped;
      continue;
    }
    final char = source[i];
    if (depth == 0 && (char == '\n' || _startsDeclaration(source, i))) break;
    if (char == '(' || char == '[') depth++;
    if (char == ')' || char == ']') depth--;
    i++;
    lastToken = i;
  }
  return lastToken;
}

/// Index of the `}` closing the brace at [open], or null if unbalanced.
int? _matchingBrace(String source, int open) {
  var depth = 0;
  var i = open;
  while (i < source.length) {
    final skipped = _skipTrivia(source, i);
    if (skipped != i) {
      i = skipped;
      continue;
    }
    final char = source[i];
    if (char == '{') depth++;
    if (char == '}') {
      depth--;
      if (depth == 0) return i;
    }
    i++;
  }
  return null;
}

/// Advances past whitespace, comments and string literals starting at [i].
///
/// Returns [i] unchanged when there is no trivia there, which is how callers
/// tell "consumed something" from "look at this character".
int _skipTrivia(String source, int i) {
  final char = source[i];

  if (char == ' ' || char == '\t' || char == '\r' || char == '\n') return i + 1;

  if (source.startsWith('//', i)) {
    final newline = source.indexOf('\n', i);
    return newline == -1 ? source.length : newline;
  }

  if (source.startsWith('/*', i)) {
    final close = source.indexOf('*/', i + 2);
    return close == -1 ? source.length : close + 2;
  }

  if (source.startsWith('"""', i)) {
    final close = source.indexOf('"""', i + 3);
    return close == -1 ? source.length : close + 3;
  }

  if (char == '"' || char == "'") {
    var j = i + 1;
    while (j < source.length) {
      if (source[j] == r'\') {
        j += 2;
        continue;
      }
      if (source[j] == char) return j + 1;
      if (source[j] == '\n') break; // unterminated; treat as an ordinary char
      j++;
    }
    return i + 1;
  }

  return i;
}
