package com.example.mybird_test

import io.flutter.embedding.android.FlutterActivity

class MainActivity : FlutterActivity() {
    // flutter_ota:begin — generated by `flutter_ota init`; edits are overwritten
    override fun getFlutterShellArgs(): io.flutter.embedding.engine.FlutterShellArgs =
        dev.flutterota.FlutterOtaPatch.applyTo(this, super.getFlutterShellArgs())
    // flutter_ota:end
}
